// Fetch Latin-subset woff2 for the two non-auto-resolved brand fonts and emit a
// local fonts/fonts.css with @font-face blocks pointing at the downloaded files.
import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const FONTS_DIR = `${here}/fonts`;
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@700;800&family=Hanken+Grotesk:wght@400;500;600&display=swap";

const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

// Split into @font-face blocks; keep only the Latin subset (the block whose
// unicode-range includes U+0000-00FF), which is all this composition needs.
const blocks = css.split("@font-face").slice(1).map((b) => "@font-face" + b.split("}")[0] + "}");
let out = "/* AUTO-GENERATED by fetch-fonts.mjs — local Latin woff2 for the brand fonts. */\n";
let n = 0;
await mkdir(FONTS_DIR, { recursive: true });

for (const block of blocks) {
  if (!/U\+0000-00FF/.test(block)) continue; // latin only
  const fam = (block.match(/font-family:\s*'([^']+)'/) || [])[1] || "font";
  const wght = (block.match(/font-weight:\s*(\d+)/) || [])[1] || "400";
  const url = (block.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
  if (!url) continue;
  const slug = fam.toLowerCase().replace(/[^a-z0-9]+/g, "-") + "-" + wght;
  const file = `${slug}.woff2`;
  const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
  await writeFile(`${FONTS_DIR}/${file}`, buf);
  console.log(`  ✓ ${fam} ${wght} → fonts/${file} (${Math.round(buf.length / 1024)}KB)`);
  out += `@font-face {\n  font-family: '${fam}';\n  font-style: normal;\n  font-weight: ${wght};\n  font-display: swap;\n  src: url('fonts/${file}') format('woff2');\n}\n`;
  n++;
}

await writeFile(`${FONTS_DIR}/fonts.css`, out);
console.log(`\nWrote ${n} @font-face → fonts/fonts.css`);
