/**
 * Seed the feed with REAL Walrus media (dev/demo only).
 *
 * Uploads the ffmpeg-generated sample clips + posters in /tmp/suinami-seed to
 * the Walrus testnet publisher (each `send_object_to` a per-creator address),
 * then writes apps/web/src/feed/sampleFeed.ts — a typed FeedCard[] the web feed
 * consumes EXACTLY like GET /api/feed, so swapping to the real indexer later is
 * a one-line change.
 *
 * Run from the repo root:  pnpm seed:walrus
 */
import { config as loadEnv } from "dotenv";
import { randomBytes } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import process from "node:process";

import { blobUrl, storeBlob } from "@suinami/walrus";

const here = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(here, "../../..");
loadEnv({ path: resolve(REPO_ROOT, ".env") });

const publisherUrl = process.env.WALRUS_PUBLISHER_URL ?? "";
const aggregatorUrl = process.env.WALRUS_AGGREGATOR_URL ?? "";
const epochs = Number(process.env.WALRUS_DEFAULT_EPOCHS ?? "5");
const SEED_DIR = "/tmp/suinami-seed";
const OUT = resolve(REPO_ROOT, "apps/web/src/feed/sampleFeed.ts");

interface Seed {
  i: number;
  handle: string;
  caption: string;
  likeCount: number;
  viewCount: number;
  tipSui: number;
}

const SEEDS: Seed[] = [
  { i: 1, handle: "deepcurrent", caption: "lost in the mandel-tide 🌀", likeCount: 1284, viewCount: 20431, tipSui: 3.2 },
  { i: 2, handle: "aquaflow", caption: "ocean gradient mood 🌊", likeCount: 842, viewCount: 9120, tipSui: 1.1 },
  { i: 3, handle: "signalsurf", caption: "testing the waters 📺", likeCount: 367, viewCount: 4501, tipSui: 0.4 },
  { i: 4, handle: "tidepool", caption: "tiny lives, big waves 🦠", likeCount: 2103, viewCount: 38770, tipSui: 6.7 },
  { i: 5, handle: "reefbits", caption: "cellular currents 🪸", likeCount: 559, viewCount: 7044, tipSui: 0.9 },
  { i: 6, handle: "sunsetswell", caption: "golden hour swell 🌅", likeCount: 1777, viewCount: 15992, tipSui: 4.5 },
];

const MIST_PER_SUI = 1_000_000_000;

/** Retry transient publisher failures (ECONNRESET / fetch failed) with backoff. */
async function withRetry<T>(fn: () => Promise<T>, label: string, tries = 5): Promise<T> {
  let lastErr: unknown;
  for (let a = 1; a <= tries; a++) {
    try {
      return await fn();
    } catch (e) {
      lastErr = e;
      console.log(`   ⟳ ${label} attempt ${a}/${tries} failed (${(e as Error).message}); retrying…`);
      await new Promise((r) => setTimeout(r, 2500 * a));
    }
  }
  throw lastErr;
}

async function main(): Promise<void> {
  if (!publisherUrl || !aggregatorUrl) {
    console.error("✗ WALRUS_PUBLISHER_URL / WALRUS_AGGREGATOR_URL missing in .env");
    process.exit(1);
  }
  const baseTime = Date.now();

  // Sequential (one blob at a time) — the hosted publisher resets on concurrent
  // large PUTs. Each upload is retried on transient ECONNRESET.
  const cards = [];
  for (const s of SEEDS) {
    const creator = `0x${randomBytes(32).toString("hex")}`;
    const videoBytes = readFileSync(`${SEED_DIR}/clip${s.i}.mp4`);
    const posterBytes = readFileSync(`${SEED_DIR}/poster${s.i}.jpg`);
    console.log(`↑ clip${s.i} (@${s.handle}) — ${Math.round(videoBytes.length / 1024)}KB video + ${Math.round(posterBytes.length / 1024)}KB poster …`);
    const video = await withRetry(
      () => storeBlob(videoBytes, { publisherUrl, epochs, sendObjectTo: creator }),
      `clip${s.i} video`,
    );
    const poster = await withRetry(
      () => storeBlob(posterBytes, { publisherUrl, epochs, sendObjectTo: creator }),
      `clip${s.i} poster`,
    );
    console.log(`  ✓ @${s.handle}: video=${video.blobId.slice(0, 10)}… poster=${poster.blobId.slice(0, 10)}…`);
    cards.push({
      videoId: `seed:${s.i}`,
      creator,
      handle: s.handle,
      avatarUrl: null as string | null,
      videoUrl: blobUrl(aggregatorUrl, video.blobId),
      posterUrl: blobUrl(aggregatorUrl, poster.blobId),
      caption: s.caption,
      likeCount: s.likeCount,
      viewCount: s.viewCount,
      tipTotal: String(Math.round(s.tipSui * MIST_PER_SUI)),
      durationMs: 6000,
      width: 720,
      height: 1280,
      createdAt: baseTime - s.i * 3_600_000,
    });
  }

  const body = `/**
 * AUTO-GENERATED by apps/api/scripts/seed-walrus.ts — DO NOT hand-edit.
 * REAL Walrus testnet media: every videoUrl/posterUrl is a live Walrus
 * aggregator blob URL. Shape is identical to GET /api/feed (FeedCard).
 * The app reads GET /api/feed (real on-chain Videos); this manifest is the
 * graceful fallback used when the API is empty or unreachable.
 */
import type { FeedCard } from "@suinami/shared";

export const SAMPLE_FEED: FeedCard[] = ${JSON.stringify(cards, null, 2)};
`;
  writeFileSync(OUT, body);
  console.log(`\n✓ wrote ${cards.length} real-Walrus cards → ${OUT}`);
  console.log("  Verify one in a browser:");
  console.log(`  ${cards[0]?.videoUrl}`);
}

main().catch((err: unknown) => {
  console.error("✗ seed-walrus failed:", err);
  process.exit(1);
});
